config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/' => 'home#index', as: :home
  root 'home#index'
  get '/about' => 'home#about'
  get '/contact' => 'home#contact'
  get '/faq' => 'home#faq'
  post '/contact_submit' => 'home#contact_submit'

  # resources :questions do
  #   post 'comments' =>'comments#create'
  # end
  resources :tags, only: [:index, :show]
  resources :favorites, only: :index
  resources :products, shallow: true do
    resources :favorites, only: [:create, :destroy]
    # resources :comments, only: [:create]
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  namespace :admin do
    # get 'questions' => 'questions#index'
    #WTF is this doing?
    resources :questions
    # get '/products/new' => 'products#new', as: :new_product
    # post '/products/new' => 'products#create', as: :create_product
  end


end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favoriting_users, through: :favorites, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :category
  belongs_to :user
  before_save :capitalize_title
  before_validation :set_defaults

  validates :title, presence: true,
            uniqueness: {case_sensitive: false}

  validates :price, presence: true, numericality: {greater_than: 0}

  validates :sale_price, numericality: {less_than_or_equal_to: :price}

  validates :description, presence: true,
            length: {minimum: 10}

  validate :no_competition
  #
  # def self.search (keyword)
  #   self.where('products.title ILIKE :query OR products.description ILIKE :query', query: "%#{keyword}%")
  # end
  #

    RESERVED_WORDS = [
      'Microsoft',
      'Sony',
      'Apple'
    ]

    def no_competition
      if /#{RESERVED_WORDS.join('|')}/ === description
        errors.add(StandardError.new(:description), "We don't like competition!")
      end
    end

  def on_sale?
    self.sale_price < self.price
  end

  def self.search(search_str)
    where("title ILIKE ? OR description ILIKE ?", "%#{search_str}%", "%#{search_str}%")
  end
  #
  # def self.search_sort_paginate(search_str, sort_by_column, current_page, per_page_count)
  #   where("title ILIKE ? OR description ILIKE ?", "%#{search_str}%", "%#{search_str}%").
  #   order(sort_by_column.to_s).
  #   offset((current_page-1)*per_page_count).
  #   limit(per_page_count)
  # end

  def favorite_for(user)
    favorites.find_by(user: user)
  end

  private
  def set_defaults
    self.sale_price ||= self.price
    self.hit_count ||= 1
  end

  def capitalize_title
    self.title = self.title.capitalize
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user, except: [:index, :show]

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).
      order(params[:sort_by]).page(params[:page]).per(10)
      # @products = Product.search_title_desc(params[:search]).order(title: :ASC).page(params[:page]).per(10)
    else
     @products = Product.order(title: :ASC).page(params[:page]).per(10)
   end

   respond_to do |format|
     format.html {render}
     format.json {render json: @products.to_json}
   end
  end

  def new
    @product = Product.new
  end

  def create
    product_params = params.require(:product).permit([:title, :description, :price, :category_id, tag_ids: []])
    @product = Product.new product_params
    @user = current_user
    @product.user = @user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new
    @favorite = @product.favorite_for(current_user)
    Product.increment_counter(:hit_count, @product[:id])
    respond_to do |format|
      format.html {render}
      format.json {render json: @product.to_json(include: :reviews)}
    end
  end

  def edit
    @product = Product.find(params[:id])
    if cannot? :manage_product, @product
      redirect_to product_path(@product), alert: 'Access Denied!'
    end
  end

  def update
    @product = Product.find(params[:id])
    product_params = params.require(:product).permit(:title, :description, :price, tag_ids: [])
    if cannot? :manage_product, @product
      redirect_to product_path(@product), alert: 'Access Denied!'
    elsif @product.update product_params
      redirect_to product_path(@product), notice: 'Saved product changes.'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if cannot? :manage_product, @product
      redirect_to product_path(@product), alert: 'Access Denied!'
    elsif @product.destroy
      redirect_to products_path, notice: 'Product deleted.'
    else
      redirect_to product_path(@product), alert: @product.errors.full_messages.join(", ")
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= @product.errors.full_messages.join(', ') %>
<%= form_for @product do |p| %>
  <div>
    <%= p.label :title%>
    <%= p.text_field :title %>
  </div>
  <div>
    <%= p.label :category_id %>
    <%= p.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div>
    <%= p.label :description%>
    <%= p.text_field :description %>
  </div>
  <div>
    <%= p.label :tag_ids, 'Tags' %>
    <%= p.collection_select(
  :tag_ids, Tag.all, :id, :name, {},
  {multiple: true, class: 'chosen-select' }
) %>
  </div>
  <div>
    <%= p.label :price%>
    <%= p.text_field :price %>
  </div>
  <%= p.submit %>
  <% end %>

  <script>
  $('.chosen-select').chosen({width: '300px'})
  </script>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form', {btn_label: 'Save Changes'} %>

app/views/products/index.html.erb
<h1 class="search_page_title">Products</h1>
<div class="search_box">
  <%= form_tag(products_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
  <%= submit_tag "Search" %><br>
  <%= label_tag :sort_by, nil, class: 'sort_label'%>
  <%= select_tag :sort_by, options_for_select([['Relevance','title'], ['Price: Low to High', 'price'], ['Price: High to Low', 'price'], ['Most Popular', 'hit_count'], ['Newest Arrivals', 'created_at']])  %>
  <% end %>
</div>


<br>
<div style="clear:both">
<% if !@products.present? %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% else %>
  <% @products.each do |p| %>
    <%= link_to p.title, product_path(p) %>
    <hr>
  <% end %>
<% end %>
</div>
<div class="paginator"><%= paginate @products %></div>

app/views/products/new.html.erb
<h1>Add New Product</h1>
<%= render 'form', {btn_label: 'Submit'} %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
by <%= @product.user.first_name %> <%= @product.user.last_name %><br>
Price: <%= number_to_currency(@product.price) %>
<p><%= @product.description %><br><br>
Category: <%= @product.category.name %><br>
Tags: <%=  @product.tags.map(&:name).join(', ')%><br>
Views: <%= @product.hit_count %></p>

<% if user_signed_in? %>
  <% if can? :manage_product, @product %>
  <%= link_to 'edit', edit_product_path(@product)%>
  <%= link_to 'delete', product_path(@product),
                        method: :delete,
                        data: {confirm: 'Are you sure?'}%>
  <% end %>
  <% if can? :favorite, @product %>
    <% if @favorite.present? %>
      <%= link_to 'unfavorite', favorite_path(@favorite), method: :delete %>
    <% else %>
      <%= link_to 'favorite', product_favorites_path(@product), method: :post%>
    <% end %>
  <% end %>
<% end %>
<hr>
<% if can? :review, @product %>
  <h2>Write a Review</h2>
  <div id="review-form">
    <%= render 'reviews/form' %>
  </div>
<% end %>
<h2>Reviews</h2>
<div id="reviews">
  <% @product.reviews.each do |review| %>
    <%= render 'reviews/review', {rev: review} %>
  <% end %>
</div>