config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/' => 'home#index', as: :home
  root 'home#index'
  get '/about' => 'home#about'
  get '/contact' => 'home#contact'
  get '/faq' => 'home#faq'
  post '/contact_submit' => 'home#contact_submit'

  # resources :questions do
  #   post 'comments' =>'comments#create'
  # end
  resources :tags, only: [:index, :show]
  resources :favorites, only: :index
  resources :products, shallow: true do
    resources :favorites, only: [:create, :destroy]
    # resources :comments, only: [:create]
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  namespace :admin do
    # get 'questions' => 'questions#index'
    #WTF is this doing?
    resources :questions
    # get '/products/new' => 'products#new', as: :new_product
    # post '/products/new' => 'products#create', as: :create_product
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user


  def create
    @product = Product.find(params[:product_id])
    review_params = params.require(:review).permit(:body, :star_count)
    @review = Review.new review_params
    @review.product = @product
    @user = current_user
    @review.user = @user

    respond_to do |format|

      if cannot? :review, @product
        format.js {render :create_failure}
        format.html {redirect_to product_path(@product), notice: 'Cannot review your own product!'}
      elsif @review.save
        ReviewsMailer.notify_product_owner(@review).deliver_now
        Product.decrement_counter(:hit_count, @product[:id])
        format.js {render :create_success}
        format.html { redirect_to product_path(@product), notice: 'Review added successfully.'}
      else
        format.js {render :create_failure}
        format.html { render 'products/show' }
      end

    end
  end

  def destroy
    # @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @product = @review.product
    Product.decrement_counter(:hit_count, @product[:id])

    respond_to do |format|

      if (can?(:destroy_review, @review) && @review.destroy)
        format.js {render}
        format.html {redirect_to product_path(@product), notice: "Review deleted successfully."}
      else
        format.html { redirect_to root_path, alert: 'Access Denied'}
        format.js { render js: 'alert("Access denied.")'; }
      end

    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= @review.errors.full_messages.join(', ') %>
<div>
<%= form_for [@product, @review], remote: true do |f| %>
  <div>
    <%= f.text_area :body %>
    <br>
    <%= f.label :star_count, 'Number of Stars: ', class: 'star_label' %>
    <%= f.select :star_count, options_for_select(1..5, @review.star_count) %>
  </div>
  <%= f.submit %>
<% end %>
<hr/>
</div>

app/views/reviews/_review.html.erb
<div id="<%= dom_id(rev) %>">
  Rating:
   <% rev.star_count.to_i.times do %>
   🌟
   <% end %>
   <% (5-rev.star_count.to_i).times do %>
   ☆
   <% end %>
 <br>
  by <%= rev.user.first_name %> <%= rev.user.last_name %> on <%= rev.created_at.strftime("%b. %e, %Y") %>
  <br><br>
  <%= rev.body %>
  <br>
  <br>
  <% if user_signed_in? && can?(:destroy_review, rev) %>
    <%= link_to 'delete', review_path(rev),
                          remote: true,
                          method: :delete,
                          data: {confirm: 'Are you sure?'}%>
  <% end %>
  <div class="likes">
    <%= render 'likes/like', {rev: rev} %>
  </div>
  <hr>
</div>

app/views/reviews/create_failure.js.erb
$('#review-form').html('<%= j render 'form' %>');

app/views/reviews/create_success.js.erb
$('#reviews').prepend("<%= j render 'review', rev: @review %>");
$('#reviews').children().first().hide();
<% @review = Review.new %>
$('#review-form').html('<%= j render 'form' %>');
$('#reviews').children().first().fadeIn(800);

app/views/reviews/destroy.js.erb
$("#<%= dom_id(@review) %>").fadeOut(800, function(){$(this).remove(); });